name: De Reizigers
favicon: null
layout_spectrum: 0.7549437959678471
typography_spectrum: 0.40415986464358866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20431240950711071
  lightness: 0.638873620191589
  saturation: 0.8866239795461297
  rhythmicContrast: 0.7890050194691867
purpose: []
